# Generated by Django 4.2.4 on 2024-01-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('para', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
