# Generated by Django 4.2.4 on 2024-01-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='para',
            new_name='content',
        ),
    ]
