# Generated by Django 4.2.4 on 2024-01-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_para_facilities_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='colour',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
