# Generated by Django 4.2.4 on 2024-01-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/teachers')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='Time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
